# Ufunc Config

> Auto-generated documentation for [env.Lib.site-packages.numpy.core._ufunc_config](..\..\..\..\..\..\env\Lib\site-packages\numpy\core\_ufunc_config.py) module.

Functions for changing global ufunc configuration

- [Smart-house-rest-api](..\..\..\..\..\README.md#description) / [Modules](..\..\..\..\..\MODULES.md#smart-house-rest-api-modules) / `Env` / `Lib` / `Site-packages` / [Numpy](..\index.md#numpy) / [Core](index.md#core) / Ufunc Config
    - [errstate](#errstate)
    - [getbufsize](#getbufsize)
    - [geterr](#geterr)
    - [geterrcall](#geterrcall)
    - [setbufsize](#setbufsize)
    - [seterr](#seterr)
    - [seterrcall](#seterrcall)

This provides helpers which wrap `umath.geterrobj` and `umath.seterrobj`

## errstate

[[find in source code]](..\..\..\..\..\..\env\Lib\site-packages\numpy\core\_ufunc_config.py#L369)

```python
set_module('numpy')
class errstate(contextlib.ContextDecorator):
    def __init__(call=_Unspecified, **kwargs):
```

errstate(**kwargs)

Context manager for floating-point error handling.

Using an instance of [errstate](#errstate) as a context manager allows statements in
that context to execute with a known error handling behavior. Upon entering
the context the error handling is set with [seterr](#seterr) and [seterrcall](#seterrcall), and
upon exiting it is reset to what it was before.

..  versionchanged:: 1.17.0
    [errstate](#errstate) is also usable as a function decorator, saving
    a level of indentation if an entire function is wrapped.
    See :pyclass `contextlib.ContextDecorator` for more information.

Parameters
----------
kwargs : {divide, over, under, invalid}
    Keyword arguments. The valid keywords are the possible floating-point
    exceptions. Each keyword should have a string value that defines the
    treatment for the particular error. Possible values are
    {'ignore', 'warn', 'raise', 'call', 'print', 'log'}.

See Also
--------
seterr, geterr, seterrcall, geterrcall

Notes
-----
For complete documentation of the types of floating-point exceptions and
treatment options, see [seterr](#seterr).

Examples
--------

```python
>>> from collections import OrderedDict
>>> olderr = np.seterr(all='ignore')  # Set error handling to known state.
```

```python
>>> np.arange(3) / 0.
array([nan, inf, inf])
>>> with np.errstate(divide='warn'):
...     np.arange(3) / 0.
array([nan, inf, inf])
```

```python
>>> np.sqrt(-1)
nan
>>> with np.errstate(invalid='raise'):
...     np.sqrt(-1)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
FloatingPointError: invalid value encountered in sqrt
```

Outside the context the error handling behavior has not changed:

```python
>>> OrderedDict(sorted(np.geterr().items()))
OrderedDict([('divide', 'ignore'), ('invalid', 'ignore'), ('over', 'ignore'), ('under', 'ignore')])

## getbufsize

[[find in source code]](..\..\..\..\..\..\env\Lib\site-packages\numpy\core\_ufunc_config.py#L208)

```python
@set_module('numpy')
def getbufsize():
```

Return the size of the buffer used in ufuncs.

Returns
-------
getbufsize : int
    Size of ufunc buffer in bytes.

## geterr

[[find in source code]](..\..\..\..\..\..\env\Lib\site-packages\numpy\core\_ufunc_config.py#L132)

```python
@set_module('numpy')
def geterr():
```

Get the current way of handling floating-point errors.

Returns
-------
res : dict
    A dictionary with keys "divide", "over", "under", and "invalid",
    whose values are from the strings "ignore", "print", "log", "warn",
    "raise", and "call". The keys represent possible floating-point
    exceptions, and the values define how these exceptions are handled.

See Also
--------
geterrcall, seterr, seterrcall

Notes
-----
For complete documentation of the types of floating-point exceptions and
treatment options, see [seterr](#seterr).

Examples
--------

```python
>>> from collections import OrderedDict
>>> sorted(np.geterr().items())
[('divide', 'warn'), ('invalid', 'warn'), ('over', 'warn'), ('under', 'ignore')]
>>> np.arange(3.) / np.arange(3.)
array([nan,  1.,  1.])
```

```python
>>> oldsettings = np.seterr(all='warn', over='raise')
>>> OrderedDict(sorted(np.geterr().items()))
OrderedDict([('divide', 'warn'), ('invalid', 'warn'), ('over', 'raise'), ('under', 'warn')])
>>> np.arange(3.) / np.arange(3.)
array([nan,  1.,  1.])

## geterrcall

[[find in source code]](..\..\..\..\..\..\env\Lib\site-packages\numpy\core\_ufunc_config.py#L316)

```python
@set_module('numpy')
def geterrcall():
```

Return the current callback function used on floating-point errors.

When the error handling for a floating-point error (one of "divide",
"over", "under", or "invalid") is set to 'call' or 'log', the function
that is called or the log instance that is written to is returned by
[geterrcall](#geterrcall). This function or log instance has been set with
[seterrcall](#seterrcall).

Returns
-------
errobj : callable, log instance or None
    The current error handler. If no handler was set through [seterrcall](#seterrcall),
    ``None`` is returned.

See Also
--------
seterrcall, seterr, geterr

Notes
-----
For complete documentation of the types of floating-point exceptions and
treatment options, see [seterr](#seterr).

Examples
--------

```python
>>> np.geterrcall()  # we did not yet set a handler, returns None
```

```python
>>> oldsettings = np.seterr(all='call')
>>> def err_handler(type, flag):
...     print("Floating point error (%s), with flag %s" % (type, flag))
>>> oldhandler = np.seterrcall(err_handler)
>>> np.array([1, 2, 3]) / 0.0
Floating point error (divide by zero), with flag 1
array([inf, inf, inf])
```

```python
>>> cur_handler = np.geterrcall()
>>> cur_handler is err_handler
True

## setbufsize

[[find in source code]](..\..\..\..\..\..\env\Lib\site-packages\numpy\core\_ufunc_config.py#L183)

```python
@set_module('numpy')
def setbufsize(size):
```

Set the size of the buffer used in ufuncs.

Parameters
----------
size : int
    Size of buffer.

## seterr

[[find in source code]](..\..\..\..\..\..\env\Lib\site-packages\numpy\core\_ufunc_config.py#L32)

```python
@set_module('numpy')
def seterr(all=None, divide=None, over=None, under=None, invalid=None):
```

Set how floating-point errors are handled.

Note that operations on integer scalar types (such as `int16`) are
handled like floating point, and are affected by these settings.

Parameters
----------
all : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Set treatment for all types of floating-point errors at once:

- ignore: Take no action when the exception occurs.
- warn: Print a `RuntimeWarning` (via the Python `warnings` module).
- raise: Raise a `FloatingPointError`.
- call: Call a function specified using the [seterrcall](#seterrcall) function.
- print: Print a warning directly to ``stdout``.
- log: Record error in a Log object specified by [seterrcall](#seterrcall).

    The default is not to change the current behavior.
divide : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Treatment for division by zero.
over : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Treatment for floating-point overflow.
under : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Treatment for floating-point underflow.
invalid : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Treatment for invalid floating-point operation.

Returns
-------
old_settings : dict
    Dictionary containing the old settings.

See also
--------
seterrcall : Set a callback function for the 'call' mode.
geterr, geterrcall, errstate

Notes
-----
The floating-point exceptions are defined in the IEEE 754 standard [1]_:

- Division by zero: infinite result obtained from finite numbers.
- Overflow: result too large to be expressed.
- Underflow: result so close to zero that some precision
  was lost.
- Invalid operation: result is not an expressible number, typically
  indicates that a NaN was produced.

.. [1] https://en.wikipedia.org/wiki/IEEE_754

Examples
--------

```python
>>> old_settings = np.seterr(all='ignore')  #seterr to known value
>>> np.seterr(over='raise')
{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}
>>> np.seterr(**old_settings)  # reset to default
{'divide': 'ignore', 'over': 'raise', 'under': 'ignore', 'invalid': 'ignore'}
```

```python
>>> np.int16(32000) * np.int16(3)
30464
>>> old_settings = np.seterr(all='warn', over='raise')
>>> np.int16(32000) * np.int16(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: overflow encountered in short_scalars
```

```python
>>> from collections import OrderedDict
>>> old_settings = np.seterr(all='print')
>>> OrderedDict(np.geterr())
OrderedDict([('divide', 'print'), ('over', 'print'), ('under', 'print'), ('invalid', 'print')])
>>> np.int16(32000) * np.int16(3)
30464

## seterrcall

[[find in source code]](..\..\..\..\..\..\env\Lib\site-packages\numpy\core\_ufunc_config.py#L222)

```python
@set_module('numpy')
def seterrcall(func):
```

Set the floating-point error callback function or log object.

There are two ways to capture floating-point error messages.  The first
is to set the error-handler to 'call', using [seterr](#seterr).  Then, set
the function to call using this function.

The second is to set the error-handler to 'log', using [seterr](#seterr).
Floating-point errors then trigger a call to the 'write' method of
the provided object.

Parameters
----------
func : callable f(err, flag) or object with write method
    Function to call upon floating-point errors ('call'-mode) or
    object whose 'write' method is used to log such message ('log'-mode).

The call function takes two arguments. The first is a string describing
the type of error (such as "divide by zero", "overflow", "underflow",
or "invalid value"), and the second is the status flag.  The flag is a
byte, whose four least-significant bits indicate the type of error, one
of "divide", "over", "under", "invalid"

```python
[0 0 0 0 divide over under invalid]
```

In other words, ``flags = divide + 2*over + 4*under + 8*invalid``.

If an object is provided, its write method should take one argument,
a string.

Returns
-------
h : callable, log instance or None
    The old error handler.

See Also
--------
seterr, geterr, geterrcall

Examples
--------
Callback upon error:

```python
>>> def err_handler(type, flag):
...     print("Floating point error (%s), with flag %s" % (type, flag))
...
```

```python
>>> saved_handler = np.seterrcall(err_handler)
>>> save_err = np.seterr(all='call')
>>> from collections import OrderedDict
```

```python
>>> np.array([1, 2, 3]) / 0.0
Floating point error (divide by zero), with flag 1
array([inf, inf, inf])
```

```python
>>> np.seterrcall(saved_handler)
<function err_handler at 0x...>
>>> OrderedDict(sorted(np.seterr(**save_err).items()))
OrderedDict([('divide', 'call'), ('invalid', 'call'), ('over', 'call'), ('under', 'call')])
```

Log error message:

```python
>>> class Log:
...     def write(self, msg):
...         print("LOG: %s" % msg)
...
```

```python
>>> log = Log()
>>> saved_handler = np.seterrcall(log)
>>> save_err = np.seterr(all='log')
```

```python
>>> np.array([1, 2, 3]) / 0.0
LOG: Warning: divide by zero encountered in true_divide
array([inf, inf, inf])
```

```python
>>> np.seterrcall(saved_handler)
<numpy.core.numeric.Log object at 0x...>
>>> OrderedDict(sorted(np.seterr(**save_err).items()))
OrderedDict([('divide', 'log'), ('invalid', 'log'), ('over', 'log'), ('under', 'log')])
